name: Daily Audio Processing

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  process_audio:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List audio files
      run: |
        Get-ChildItem -Path .\audio\ -Filter *.your_file_extension_here | ForEach-Object { Write-Host $_.FullName } | Out-File -Encoding utf8 -FilePath audio_files.txt

    - name: Download audioChunkSplitter.py
      run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/regallasandeepkumarreddy11/MyAutomation/master/audio/audioChunkSplitter.py -OutFile audioChunkSplitter.py

    - name: Process audio files
      run: |
        Get-Content audio_files.txt | ForEach-Object {
          # Add the command to process each file using audioChunkSplitter.py
          python audioChunkSplitter.py $_
        }
