name: Python CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        .\venv\Scripts\activate

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your requirements file

    # - name: Run audioChunkSplitter.py and write output to file
    #   run: |
    #     python ./audio/audioChunkSplitter.py > output.txt  # Replace with the correct path to your script and desired output file name
