name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted


    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
        
    - name: Checkout repository
      uses: actions/checkout@v2

