name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        .\venv\Scripts\activate
        
    - name: Run audioChunkSplitter.py
      run: |
        python ./audio/audioChunkSplitter.py  # Replace with the correct path to your script
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your requirements file
        

