name: Python CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and activate virtual environment
      run: |
        C:\Python38\python -m venv venv
        .\venv\Scripts\activate

    - name: Install dependencies
      run: |
        C:\Python38\Scripts\pip install -r C:\MyAutomation\requirements.txt  # Replace with your requirements file

    - name: Run audioChunkSplitter.py and write output to file
      run: |
        python ./audio/playAudioFile.py
        python ./audio/audioVerify.py
        

